### PR TITLE
Add non-carrier Note9 model number

### PR DESCRIPTION
**Pull request by Liz-chan**
This works fine on carrier Note9 firmwares, but not on phones flashed with the U1 firmware.

### CODE REVIEW

**Comment by thestinger** [comment]
The string for the verified boot key that it gets matched against also needs to be updated to include this model.

**Comment by thestinger** [comment]
I haven't gone through all the samples and dealt with them all for a while so we're very behind on device support right now.

**Comment by Liz-chan** [comment]
I'm not sure how to get the part in AttestationProtocol.java but I submitted a sample for you to have a look when you can.

**Comment by thestinger** [comment]
Not going to have time to expand device support for the foreseeable future, unfortunately. Need someone to help with making tooling to make it easier and to help with adding the devices with it. Can't add this without testing.

**Pull request closed without merging**
