### PR TITLE
Add support for the Samsung Galaxy Z Flip3 5G (SM-F711B)

### PR DESCRIPTION
**Pull request by dbaxa**
Signed-off-by: David Black <dblack@atlassian.com>

### CODE REVIEW

**Comment by dbaxa** [comment]
cc @thestinger

**Comment by Zanthed** [comment]
Have you tested this with your own local builds of Auditor?

**Comment by dbaxa** [comment]
> Have you tested this with your own local builds of Auditor?

Yes.

**Comment by Zanthed** [comment]
Make a PR to add it to attestation.app here as well: https://github.com/GrapheneOS/AttestationServer/

If you need a server to test I can spin up my instance, though it should be fine.

**Comment by dbaxa** [comment]
I have raised https://github.com/GrapheneOS/AttestationServer/pull/187

**Comment by thestinger** [comment]
We need a project member to verify this and we're not set up for that right now. We're supposed to be doing this ourselves with the submitted samples, but we lack the resources to do it. We're also supposed to be adding samples for each added device to our samples repository which is important for maintenance. We stopped doing it for Pixels due to no longer actively using the actual sample submissions primarily due to lack of tooling.

If you want us to add more devices, what you should work on is making better tooling for automating this work including the sample handling so we can add all the devices with valid submitted samples instead of just one specific device.

I don't think we can accept these pull requests. It needs to be done in a different way.

**Comment by dbaxa** [comment]
Hi @thestinger, 
What kind of automation would we like to end up having though? 

It seems like for security reasons we end up having the "properties" (`verifiedBootKey`) and "attributes" (version info &  backing type) in a relatively easy accessible fashion from samples - would the automation make it easy to raise PRs for the different repos and or update some kind of (mostly shared) state/database containing device related information?

**Comment by thestinger** [comment]
The main thing that needs to be done is verifying that it's a valid sample based on one of Google's roots and extracting the different properties from, along with testing that it passes verification with all the usual verification code. Sometimes there are bugs which you can see with our workaround setup for some older Samsung devices. It seems that isn't needed anymore if this works without it.

**Comment by thestinger** [comment]
Also, we need to test verifying both with and without StrongBox. Auditor will only use StrongBox but I like to know that we have the correct setup for TEE too. It can be a different attestation version, etc. which was often the case on Pixels before the Pixel 6 since it was Qualcomm's QSEE TEE implementation and the Titan M so Google was often ahead of Qualcomm.

**Comment by dbaxa** [comment]
>Also, we need to test verifying both with and without StrongBox. Auditor will only use StrongBox but I like to know that we have the correct setup for TEE too.

Interesting. Do we have reason to check without strongbox - even for testing a correct TEE setup ... if strong box is available for a device?

**Comment by dbaxa** [comment]
> Sometimes there are bugs which you can see with our workaround setup for some older Samsung devices. It seems that isn't needed anymore if this works without it.

Yeah I saw that. This device works without the workaround it seems.

**Comment by dbaxa** [comment]
@thestinger ^ is it possible to add some more details to this so that others might work on possible changes/automation?

**Comment by thestinger** [comment]
I can try providing some more details later.

**Comment by dbaxa** [comment]
Nudge @thestinger :-)

**Comment by thestinger** [comment]
@dbaxa Gave some information to @flawedworld about what is needed to build a tool for generating the data from samples and verifying samples automatically.

**Comment by dbaxa** [comment]
Hi @thestinger, Right okay. Are there things that others can do to help :-) ?

**Comment by flawedworld** [comment]
@dbaxa Hi, so for a brief overview:

We have sample attestations here: https://github.com/GrapheneOS/AttestationSamples

We need a CLI tool which can basically take the attestation chain of the der encoded certs (note that the chain length can vary) for TEE and StrongBox respectively (if supported on the device) and validate it with the attestation APIs against the Google Attestation CA. If valid, it should then provide a copy/paste code snippet (basically what you have added to this repo in this pull) of all the code needed to add it to Auditor and AttestationServer. This logic is already implemented in Auditor in https://github.com/GrapheneOS/Auditor/commit/5ad5e6bec5771702672903c4625faddcf5dc58a3 but it's not really feasible to do this by hand, and so we need a tool we can use to automate the authentication and addition of new device data.

**Comment by thestinger** [comment]
I got tired of doing it by hand. It's too time consuming to copy paste them in base64 format into that array and verify with the app with multiple steps. It was done that way before AttestationServer existed, i.e. before the code could run outside the context of an Android app after I ported it over.

**Comment by dbaxa** [comment]
Hi @khartmann97  - I think I made use of https://github.com/dbaxa/Auditor/tree/debug-setup-for-adding-new-device to get the information I needed.

**Comment by ElielTad** [comment]
> Signed-off-by: David Black <dblack@atlassian.com>

**Comment by thestinger** [comment]
We're going to add generic device support instead of the previous approach. It's in development already:

https://github.com/GrapheneOS/Auditor/pull/236

**Pull request closed without merging**
