### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
the "basic starter kit" as [requested here](https://github.com/GrapheneOS/Auditor/issues/61#issuecomment-725701265). Be welcome to add screenshots (to help you out further, see my [Fastlane Cheat-Sheet](https://gitlab.com/snippets/1895688) – all important details in a way fitting on a screen without scrolling several pages). Per-Release changelogs are a nice-to-have: they are very welcome, but not essential.

As @rugk correctly pointed out, `fastlane supply` can be used to feed Play Store from the very same tree (though Play would most likely insist on having `de` renamed to eg. `de-DE` – which is kinda stupid, but it's Google so what to expect; `de` is a fully valid ISO-639 language code, but Google wants to have the locale as well, why ever). So, using the same screenshots will be perfectly fine.

Once merged, you can of course adjust everything to your liking (which is the idea behind it). I'd suggest keeping the `full_description.txt` in the current "Markdown Lite" format, which proved to work best for all:

* My repo will parse it as Markdown
* F-Droid will apply `nl2br`
* Google will… no idea, but I guess the same as F-Droid except for also replacing links by their URLs?
* we all will sanitize (to prevent "malicious stuff" like Javascript) – just mentioning that for completeness, not that we'd expect such bad things from you :laughing:

If there are any questions, just raise them. Once this is merged, I'll tell my updater to use it; once you've added screenshots please let me know so I tell my updater that as well.

### CODE REVIEW

**Comment by IzzySoft** [comment]
@thestinger @chirayudesai @divegeek any chance this will be processed? I'm about cleaning up my Github account before this year's end and drop "old forks" I don't plan to maintain – and once I drop the fork of your app, this PR will go "stale" as the source is gone.

**Comment by thestinger** [comment]
I'll handle it today. I've been quite busy and forgot about this PR.

**Comment by thestinger** [comment]
I'll probably apply it without the translation temporarily. We need to set up a proper system for updating those that doesn't get in the way and which can be properly reviewed and kept up-to-date. I don't know German so I can't really review it and won't be able to update it. It would probably be straightforward to start setting that up for Auditor, AttestationServer and PdfViewer. It would be a lot harder for the OS due to it being a downstream variant of AOSP with porting over to a new stable release every month.

**Comment by IzzySoft** [comment]
Yes, of course – feel free to cherry-pick. And for that translation system, maybe [Bubu's Weblate instance](https://weblate.bubu1.eu/)¹ could be a match – several Android FOSS apps are using it (F-Droid itself uses Weblate at least for summaries).

¹ <sub>Bubu is a member of the F-Droid core team. I know him personally and thus trust him and his instance. There are other Weblate instances if you pefer.</sub>

**Comment by thestinger** [comment]
Applied as https://github.com/GrapheneOS/Auditor/commit/86d04b36c184fd6fd788dcf485feb520682d204d. I'll have to look into setting up proper translation support at some point to deal with that part of it. A major concern for us is being able to properly review and maintain everything (strings are really important) which is difficult for that.

**Comment by IzzySoft** [comment]
> A major concern for us is being able to properly review and maintain everything (strings are really important) which is difficult for that.

Sure. To my knowledge, Weblate provides "peer review" (so a new/changed translation needs to be "approved" before becoming "official"). But I've never worked with it, so I cannot give details.

**Comment by IzzySoft** [comment]
Ugh, PS: Checking your commit I see I forgot to correct a file name. `fastlane/metadata/android/en-US/images/ic_launcher-web.png` should be `fastlane/metadata/android/en-US/images/icon.png`, sorry!

**Comment by thestinger** [comment]
Fixed, should be fine now.

>

**Comment by IzzySoft** [comment]
Thanks a lot!

**Pull request closed without merging**
